export const FriendsProfileData = [
  {
    name: 'Kavitha',
    accountName: 'kavi_11',
    profileImage: require('../assests/users/profilePic.jpeg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'Jeevitha',
    accountName: 'Jeevii_99',
    profileImage: require('../assests/users/cute.jpg'),
    posts: 24,
    followers: 1253,
    following: 64,
    follow: false,
  },

  {
    name: 'Ani_220',
    accountName: 'dharanu',
    profileImage: require('../assests/users/butterfly.jpg'),
    posts: 21,
    followers: 7886,
    following: 32,
    follow: false,
  },
  {
    name: 'paru20',
    accountName: 'Priyi_99',
    profileImage: require('../assests/users/tesla.png'),
    posts: 24,
    followers: 1253,
    following: 64,
    follow: false,
  },
  {
    name: 'Mark55',
    accountName: 'Aishuwarya',
    profileImage: require('../assests/users/teddy.jpg'),
    posts: 123,
    followers: 64253,
    following: 32,
    follow: false,
  },
  {
    name: '_cleverMind_',
    accountName: 'Don_kingmarker',
    profileImage: require('../assests/users/smile.jpeg'),
    posts: 111,
    followers: 11223,
    following: 1,
    follow: false,
  },
  {
    name: 'black_white',
    accountName: 'blackWhite',
    profileImage: require('../assests/users/kitty.jpeg'),
    posts: 121,
    followers: 43213,
    following: 21,
    follow: false,
  },
  {
    name: 'iron_man',
    accountName: 'Iron Man',
    profileImage: require('../assests/users/boy.jpg'),
    posts: 432,
    followers: '987k',
    following: 24,
    follow: false,
  },
  {
    name: 'the_jerry',
    accountName: 'The Jerry',
    profileImage: require('../assests/users/whitegirl.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'angry_bird',
    accountName: 'Angry Bird',
    profileImage: require('../assests/users/cat.jpeg'),
    posts: 452,
    followers: '564k',
    following: 31,
    follow: false,
  },
  {
    name: 'funny_videos',
    accountName: 'Funny Video Official',
    profileImage: require('../assests/users/girl.jpeg'),
    posts: '1.2k',
    followers: '1.2M',
    following: 12,
    follow: false,
  },
  {
    name: 'tanika',
    accountName: 'Tanika765',
    profileImage: require('../assests/users/kitty.jpeg'),
    posts: '1.2k',
    followers: '1.2M',
    following: 12,
    follow: false,
  },
];
