import {
  faCoffee,
  faEllipsisV,
  faSearch,
  faHeart,
  faShoppingCart,
  faArchive,
  faUser,
  faHome,
  faStar,
  faDove,
  faBars,
  faCommentDots,
  faPlusSquare,
  faComment,
  faPaperPlane,
  faBookmark,
} from '@fortawesome/free-solid-svg-icons';
import {library} from '@fortawesome/fontawesome-svg-core';
library.add(
  faSearch,
  faEllipsisV,
  faDove,
  faCommentDots,
  faCoffee,
  faPlusSquare,
  faHeart,
  faBars,
  faShoppingCart,
  faArchive,
  faUser,
  faHome,
  faStar,
  faComment,
  faBookmark,
  faPaperPlane,
);
